name: pusher_client
description: |
  A Pusher Channels client plugin for Flutter targeting Android and iOS. It 
  wraps pusher-websocket-java v2.2.5 and pusher-websocket-swift v8.0.0.
version: 2.0.0


environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.github.chinloyal.pusher_client
        pluginClass: PusherClientPlugin
      ios:
        pluginClass: PusherClientPlugin
